# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aco_algorithm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from graph import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aco_algorithm(object):
    def setupUi(self, aco_algorithm):
        aco_algorithm.setObjectName("aco_algorithm")
        aco_algorithm.resize(505, 143)
        self.verticalLayout = QtWidgets.QVBoxLayout(aco_algorithm)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(aco_algorithm)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(aco_algorithm)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(G.nodes)
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(aco_algorithm)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(aco_algorithm)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(G.nodes)
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(aco_algorithm)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(aco_algorithm)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(aco_algorithm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(aco_algorithm)
        self.buttonBox.accepted.connect(aco_algorithm.accept) # type: ignore
        self.buttonBox.rejected.connect(aco_algorithm.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(aco_algorithm)

    def retranslateUi(self, aco_algorithm):
        _translate = QtCore.QCoreApplication.translate
        aco_algorithm.setWindowTitle(_translate("aco_algorithm", "Муравьиный алгоритм"))
        self.label.setText(_translate("aco_algorithm", "Начальная вершина:"))
        self.label_2.setText(_translate("aco_algorithm", "Конечная вершина:"))
        self.label_3.setText(_translate("aco_algorithm", "Введите размер колонии:"))


    def show_data(self):
        return (self.comboBox.currentText(), self.comboBox_2.currentText(), self.lineEdit.text())


def aco_algorithm_dialog():
    global aco_algorithm
    aco_algorithm = QtWidgets.QDialog()
    ui = Ui_aco_algorithm()
    ui.setupUi(aco_algorithm)
    aco_algorithm.show()

    if aco_algorithm.exec():
        aco(ui.show_data()[0], ui.show_data()[1], int(ui.show_data()[2]))