# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connecting_vertices.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_connecting_vertices_dialog(object):
    def setupUi(self, connecting_vertices_dialog):
        connecting_vertices_dialog.setObjectName("connecting_vertices_dialog")
        connecting_vertices_dialog.setEnabled(True)
        connecting_vertices_dialog.resize(335, 143)
        self.verticalLayout = QtWidgets.QVBoxLayout(connecting_vertices_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(connecting_vertices_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(connecting_vertices_dialog)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(connecting_vertices_dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(connecting_vertices_dialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(connecting_vertices_dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(connecting_vertices_dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(connecting_vertices_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(connecting_vertices_dialog)
        self.buttonBox.accepted.connect(connecting_vertices_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(connecting_vertices_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(connecting_vertices_dialog)

    def retranslateUi(self, connecting_vertices_dialog):
        _translate = QtCore.QCoreApplication.translate
        connecting_vertices_dialog.setWindowTitle(_translate("connecting_vertices_dialog", "Соединение вершин"))
        self.label.setText(_translate("connecting_vertices_dialog", "Откуда:"))
        self.label_2.setText(_translate("connecting_vertices_dialog", "Куда:"))
        self.label_3.setText(_translate("connecting_vertices_dialog", "Введите стоимость пути:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    connecting_vertices_dialog = QtWidgets.QDialog()
    ui = Ui_connecting_vertices_dialog()
    ui.setupUi(connecting_vertices_dialog)
    connecting_vertices_dialog.show()
    sys.exit(app.exec_())
