# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connecting_vertices.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from graph import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_connecting_vertices(object):
    def setupUi(self, connecting_vertices):
        connecting_vertices.setObjectName("connecting_vertices_dialog")
        connecting_vertices.setEnabled(True)
        connecting_vertices.resize(335, 143)
        self.verticalLayout = QtWidgets.QVBoxLayout(connecting_vertices)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(connecting_vertices)
        self.label.setStyleSheet("font: 14pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(connecting_vertices)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(G.nodes)
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(connecting_vertices)
        self.label_2.setStyleSheet("font: 14pt \".AppleSystemUIFont\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(connecting_vertices)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(G.nodes)
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(connecting_vertices)
        self.label_3.setStyleSheet("font: 14pt \".AppleSystemUIFont\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(connecting_vertices)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(connecting_vertices)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(connecting_vertices)
        self.buttonBox.accepted.connect(connecting_vertices.accept) # type: ignore
        self.buttonBox.rejected.connect(connecting_vertices.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(connecting_vertices)

    def retranslateUi(self, connecting_vertices):
        _translate = QtCore.QCoreApplication.translate
        connecting_vertices.setWindowTitle(_translate("connecting_vertices", "Соединение вершин"))
        self.label.setText(_translate("connecting_vertices", "Начальная вершина:"))
        self.label_2.setText(_translate("connecting_vertices", "Конечная вершина:"))
        self.label_3.setText(_translate("connecting_vertices", "Введите стоимость пути:"))

    def show_data(self):
        return (self.comboBox.currentText(), self.comboBox_2.currentText(), self.lineEdit.text())


def connecting_vertices_dialog():
    global connecting_vertices
    connecting_vertices = QtWidgets.QDialog()
    ui = Ui_connecting_vertices()
    ui.setupUi(connecting_vertices)
    connecting_vertices.show()

    if connecting_vertices.exec():
        if ui.show_data()[2].isdigit():
            if int(ui.show_data()[2]) > 0:
                G.add_edge(ui.show_data()[0], ui.show_data()[1], weight=int(ui.show_data()[2]))
                text_output.append("Вершина " + ui.show_data()[0] + " соединена с вершиной " + ui.show_data()[1] + ".\nВес дуги: " + str(ui.show_data()[2]) + ".")
            else:
                text_output.append("Некорректный ввод.\nВес дуги должен быть положительным.")
        else:
            text_output.append("Некорректный ввод.")