# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_graph(object):
    def setupUi(self, delete_graph):
        delete_graph.setObjectName("delete_graph")
        delete_graph.resize(194, 128)
        self.verticalLayout = QtWidgets.QVBoxLayout(delete_graph)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(delete_graph)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(delete_graph)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(delete_graph)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(delete_graph)
        QtCore.QMetaObject.connectSlotsByName(delete_graph)

    def retranslateUi(self, delete_graph):
        _translate = QtCore.QCoreApplication.translate
        delete_graph.setWindowTitle(_translate("delete_graph", "Удаление графа"))
        self.label.setText(_translate("delete_graph", "<html><head/><body><p align=\"center\">Вы точно уверены, что</p><p align=\"center\">хотите удалить весь граф?</p></body></html>"))
        self.pushButton_2.setText(_translate("delete_graph", "Нет"))
        self.pushButton.setText(_translate("delete_graph", "Да"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_graph = QtWidgets.QWidget()
    ui = Ui_delete_graph()
    ui.setupUi(delete_graph)
    delete_graph.show()
    sys.exit(app.exec_())
