# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_vertex.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from graph import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_vertex(object):
    def setupUi(self, input_vertex):
        input_vertex.setObjectName("input_vertex")
        input_vertex.resize(315, 148)
        self.verticalLayout = QtWidgets.QVBoxLayout(input_vertex)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(input_vertex)
        self.label.setStyleSheet("font: 14pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(input_vertex)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(input_vertex)
        self.label_2.setStyleSheet("font: 14pt \".AppleSystemUIFont\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(input_vertex)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(input_vertex)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(input_vertex)
        self.buttonBox.accepted.connect(input_vertex.accept)  # type: ignore
        self.buttonBox.rejected.connect(input_vertex.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(input_vertex)


    def retranslateUi(self, input_vertex):
        _translate = QtCore.QCoreApplication.translate
        input_vertex.setWindowTitle(_translate("input_vertex", "Добавление вершины"))
        self.label.setText(_translate("input_vertex", "Введите название вершины: "))
        self.label_2.setText(_translate("input_vertex", "Введите значение эвристики:"))

    def show_text(self):
        return (self.lineEdit.text(), self.lineEdit_2.text())


def input_vertex_dialog():
    global input_vertex
    input_vertex = QtWidgets.QDialog()
    ui = Ui_input_vertex()
    ui.setupUi(input_vertex)
    input_vertex.show()

    if input_vertex.exec():
        if ui.show_text()[0] not in G.nodes:
            G.add_node(ui.show_text()[0], heuristics=ui.show_text()[1])
        else:
            print("Такая вершина уже существует.")
        # return ui.show_text()
